### PR TITLE
Return changed props

### PR DESCRIPTION
**Pull request by apechimp**
This pull request does the following.

1. Move pg, knex and bookshelf dependencies to `devDependencies` since they are only required by tests
2. Return a changed object of the form `{ previous: previousValue, current: currentValue }` instead of `true` when a property has changed.

### CODE REVIEW

**Comment by apechimp** [comment]
CR @lanetix/engineers

**Comment by OronNadiv** [comment]
Can you also add the property 'hasChanged': true/false

**Comment by apechimp** [comment]
@OronNadiv property added.

**Comment by OronNadiv** [comment]
I see that you either return null or a hash. Does it make sense to always return the hash and an additional property 'hasChanged'?  Seems more consistent to me.

**Comment by OronNadiv** [comment]
Also don't forget to bump the Major semver.

**Comment by apechimp** [comment]
I did that because by returning `false` or an object, it doesn't break any current consumers since all the `if(hasChanged[0]) {...}` checks don't change and we can actually just do semver minor.

**Pull request merged**
